services:
  - type: web
    name: tricycle-fare-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python check_model.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
